/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * consultaVentas.java
 *
 * Created on 09-may-2010, 20:31:41
 */

package capaGui;

import capaDatos.Ventas;
import capaNegocio.negocio;
import java.util.Iterator;
import javax.swing.JOptionPane;

/**
 *
 * @author Kamalolz
 */
public class consultaVentas extends javax.swing.JFrame {

    /** Creates new form consultaVentas */
    public consultaVentas() {
        initComponents();
        this.setLocationRelativeTo(null);
        this.llenar();

    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Consulta Ventas", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION));

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane1.setViewportView(jTextArea1);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 348, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 266, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
    * @param args the command line arguments
    */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new consultaVentas().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextArea1;
    // End of variables declaration//GEN-END:variables
    private void llenar(){
        negocio neg = new negocio();
        Iterator it = neg.getVentas().iterator();
        while (it.hasNext()) {
            Ventas vta = (Ventas) it.next();
            this.jTextArea1.append("Rut: " + vta.getRut_vta() + "-" + vta.getDigito_vta() + "\n"
                    + "Fecha: " + vta.getFecha_vta() + "\n"
                    + "Monto: " + vta.getMonto_vta() + "\n"
                    + "Número de Cuotas: " + vta.getNumCuota_vta() + "\n"
                    + "Valor de cuotas: " + vta.getValorCuota_vta() + "\n"
                    + "Interes cuotas: " + vta.getInteresCuota_vta() + "\n"
                    + "Tipo de documento: " + vta.getTipoDoc_vta() + "\n"
                    + "Descripcion de la venta: " + vta.getDescrip_vta() + "\n"
                    + "Vendedor: " + vta.getVendedor_vta() +"\n"
                    + "Sucursal: " + vta.getSucursal_vta() +"\n"
                    + "\n=====================\n");
        }
    }
}
