/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * formCliente.java
 *
 * Created on 07-may-2010, 0:06:50
 */
package capaGui;

import capaDatos.Clientes;
import capaNegocio.negocio;
import capaDatos.validaRut;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.Calendar;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author BORO
 */
public class formCliente extends javax.swing.JFrame {

    /** Creates new form formCliente */
    public formCliente() {
        initComponents();
        this.setLocationRelativeTo(null);

    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        txtNombre = new javax.swing.JTextField();
        txtRut = new javax.swing.JTextField();
        txtComuna = new javax.swing.JTextField();
        txtDomicilio = new javax.swing.JTextField();
        txtCiudad = new javax.swing.JTextField();
        txtFonos = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        txtMail = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        txtLugTrab = new javax.swing.JTextField();
        txtFechaApe = new javax.swing.JTextField();
        txtCupo = new javax.swing.JTextField();
        txtDig = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        txtRenta = new javax.swing.JTextField();
        jPanel2 = new javax.swing.JPanel();
        jLabel13 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        txtSaldoDB = new javax.swing.JTextField();
        txtSaldoCR = new javax.swing.JTextField();
        txtSaldoFinal = new javax.swing.JTextField();
        jPanel3 = new javax.swing.JPanel();
        btnBuscaRut = new javax.swing.JButton();
        btnBuscaNombre = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        btnEditar = new javax.swing.JButton();
        btnEliminar = new javax.swing.JButton();
        btnAgregarClie = new javax.swing.JButton();
        btnLimpiar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Formulario Cliente");
        setBackground(java.awt.Color.red);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Cliente"));

        jLabel7.setText("Email");

        jLabel6.setText("Fonos");

        jLabel5.setText("Ciudad");

        jLabel4.setText("Comuna");

        jLabel3.setText("Domicilio");

        jLabel10.setText("Cupo");

        jLabel8.setText("Lugar de trabajo");

        jLabel9.setText("Fecha de apertura");

        txtNombre.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtNombreKeyTyped(evt);
            }
        });

        txtRut.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtRutKeyTyped(evt);
            }
        });

        txtComuna.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtComunaKeyTyped(evt);
            }
        });

        txtDomicilio.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtDomicilioKeyTyped(evt);
            }
        });

        txtCiudad.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtCiudadKeyTyped(evt);
            }
        });

        txtFonos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtFonosActionPerformed(evt);
            }
        });
        txtFonos.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtFonosKeyTyped(evt);
            }
        });

        jLabel1.setText("Rut");

        txtMail.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtMailKeyTyped(evt);
            }
        });

        jLabel2.setText("Nombre");

        txtLugTrab.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtLugTrabActionPerformed(evt);
            }
        });
        txtLugTrab.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtLugTrabKeyTyped(evt);
            }
        });

        txtFechaApe.setEditable(false);

        txtCupo.setEditable(false);
        txtCupo.setText("0");
        txtCupo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCupoActionPerformed(evt);
            }
        });
        txtCupo.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtCupoKeyTyped(evt);
            }
        });

        txtDig.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtDigKeyTyped(evt);
            }
        });

        jLabel14.setText("-");

        jLabel15.setText("Renta Mensual:");

        txtRenta.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtRentaKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtRentaKeyTyped(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel15)
                    .addComponent(jLabel8)
                    .addComponent(jLabel3)
                    .addComponent(jLabel2)
                    .addComponent(jLabel1)
                    .addComponent(jLabel4)
                    .addComponent(jLabel5)
                    .addComponent(jLabel6)
                    .addComponent(jLabel7)
                    .addComponent(jLabel9)
                    .addComponent(jLabel10))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(txtRut, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel14)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtDig, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(txtNombre, javax.swing.GroupLayout.DEFAULT_SIZE, 213, Short.MAX_VALUE)
                    .addComponent(txtDomicilio, javax.swing.GroupLayout.DEFAULT_SIZE, 213, Short.MAX_VALUE)
                    .addComponent(txtLugTrab, javax.swing.GroupLayout.DEFAULT_SIZE, 213, Short.MAX_VALUE)
                    .addComponent(txtMail, javax.swing.GroupLayout.DEFAULT_SIZE, 213, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(txtFonos, javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(txtCiudad, javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(txtComuna, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 113, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(txtRenta, javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(txtFechaApe, javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(txtCupo, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 88, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtRut, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel14)
                    .addComponent(txtDig, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txtDomicilio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(txtComuna, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(txtCiudad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(txtFonos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(txtMail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(txtLugTrab, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtFechaApe, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel15)
                    .addComponent(txtRenta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(4, 4, 4)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtCupo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel10))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder("Saldos"));

        jLabel13.setText("Saldo final");

        jLabel11.setText("Saldo debito");

        jLabel12.setText("Abonos");

        txtSaldoDB.setEditable(false);
        txtSaldoDB.setText("0");

        txtSaldoCR.setEditable(false);
        txtSaldoCR.setText("0");

        txtSaldoFinal.setEditable(false);
        txtSaldoFinal.setText("0");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel13)
                    .addComponent(jLabel12)
                    .addComponent(jLabel11))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(txtSaldoCR, javax.swing.GroupLayout.DEFAULT_SIZE, 135, Short.MAX_VALUE)
                    .addComponent(txtSaldoDB)
                    .addComponent(txtSaldoFinal))
                .addGap(120, 120, 120))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(txtSaldoDB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel12)
                    .addComponent(txtSaldoCR, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel13)
                    .addComponent(txtSaldoFinal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder(""));

        btnBuscaRut.setIcon(new javax.swing.ImageIcon(getClass().getResource("/capaImagenes/buscar.png"))); // NOI18N
        btnBuscaRut.setText("Buscar por Rut");
        btnBuscaRut.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscaRutActionPerformed(evt);
            }
        });

        btnBuscaNombre.setIcon(new javax.swing.ImageIcon(getClass().getResource("/capaImagenes/buscar.png"))); // NOI18N
        btnBuscaNombre.setText("Buscar por nombre");
        btnBuscaNombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscaNombreActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btnBuscaRut, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 179, Short.MAX_VALUE)
                    .addComponent(btnBuscaNombre, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 179, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addComponent(btnBuscaRut)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnBuscaNombre)
                .addContainerGap())
        );

        jPanel4.setBorder(javax.swing.BorderFactory.createTitledBorder(""));

        btnEditar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/capaImagenes/editar.png"))); // NOI18N
        btnEditar.setText("Editar");
        btnEditar.setEnabled(false);
        btnEditar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditarActionPerformed(evt);
            }
        });

        btnEliminar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/capaImagenes/eliminarpng.png"))); // NOI18N
        btnEliminar.setText("Eliminar");
        btnEliminar.setEnabled(false);
        btnEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnEliminar, javax.swing.GroupLayout.DEFAULT_SIZE, 179, Short.MAX_VALUE)
                    .addComponent(btnEditar, javax.swing.GroupLayout.DEFAULT_SIZE, 179, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addComponent(btnEditar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnEliminar))
        );

        btnAgregarClie.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnAgregarClie.setIcon(new javax.swing.ImageIcon(getClass().getResource("/capaImagenes/agregar.png"))); // NOI18N
        btnAgregarClie.setText("Ingresar cliente");
        btnAgregarClie.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAgregarClieActionPerformed(evt);
            }
        });

        btnLimpiar.setText("Limpiar texto");
        btnLimpiar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLimpiarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jPanel2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 338, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnAgregarClie, javax.swing.GroupLayout.DEFAULT_SIZE, 215, Short.MAX_VALUE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(btnLimpiar, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 215, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(9, 9, 9)
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(19, 19, 19)
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnAgregarClie, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnLimpiar)))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtFonosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtFonosActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtFonosActionPerformed

    private void txtLugTrabActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtLugTrabActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtLugTrabActionPerformed

    private void btnBuscaRutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscaRutActionPerformed
        String rut = "";
        rut = JOptionPane.showInputDialog("Ingrese rut a buscar sin digito verificador");
        if (rut != null) {
            negocio neg = new negocio();
            Clientes clie = neg.getBuscarClientes(rut);

            // if ve si rut viene con datos de la forma si rut no es igual ""
            if (!clie.getRut_cli().equals("")) {
                this.txtRut.setText(clie.getRut_cli());
                this.txtDig.setText(clie.getDigito_cli());
                this.txtNombre.setText(clie.getNombre_cli());
                this.txtDomicilio.setText(clie.getDomicilio());
                this.txtComuna.setText(clie.getComuna_cli());
                this.txtCiudad.setText(clie.getCiudad_cli());
                this.txtFonos.setText(clie.getFonos_cli());
                this.txtLugTrab.setText(clie.getLugarTrabajo_cli());
                this.txtFechaApe.setText(date2string(clie.getFechApe_cli()));
                this.txtCupo.setText(clie.getCupo_cli() + "");
                this.txtMail.setText(clie.getEmail_cli());

                this.txtSaldoDB.setText(neg.getDebito(rut) + "");
                this.txtSaldoCR.setText(neg.getSaldoPagado(rut) + "");
                int saldoFinal = neg.getDebito(rut) - neg.getSaldoPagado(rut);
                this.txtSaldoFinal.setText(saldoFinal + "");
                this.habilitarELimYEdit();


//               this.habilitarBotones();

            } else {
                JOptionPane.showMessageDialog(null,
                        "Error. Rut no existe");
            }
        }




    }//GEN-LAST:event_btnBuscaRutActionPerformed

    private void btnAgregarClieActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgregarClieActionPerformed

        //TODO validadndo ingreso de datos

        if (this.txtRut.getText().trim().isEmpty()) {
            JOptionPane.showMessageDialog(null,
                    "Error debe ingresar el rut",
                    "Error de ingreso",
                    JOptionPane.ERROR_MESSAGE);
            this.txtRut.requestFocus();
            return;

        }

        if (this.txtDig.getText().trim().isEmpty()) {
            JOptionPane.showMessageDialog(null,
                    "Error debe ingresar el digito verificador del rut",
                    "Error de ingreso",
                    JOptionPane.ERROR_MESSAGE);
            this.txtDig.requestFocus();
            return;

        }
        if (this.txtNombre.getText().trim().isEmpty()) {
            JOptionPane.showMessageDialog(null,
                    "Error debe ingresar el nombre",
                    "Error de ingreso",
                    JOptionPane.ERROR_MESSAGE);
            this.txtNombre.requestFocus();
            return;

        }



        if (this.txtDomicilio.getText().trim().isEmpty()) {
            JOptionPane.showMessageDialog(null,
                    "Error debe ingresar el Domicilio",
                    "Error de ingreso",
                    JOptionPane.ERROR_MESSAGE);
            this.txtDomicilio.requestFocus();
            return;

        }

        if (this.txtComuna.getText().trim().isEmpty()) {
            JOptionPane.showMessageDialog(null,
                    "Error debe ingresar la Comuna",
                    "Error de ingreso",
                    JOptionPane.ERROR_MESSAGE);
            this.txtComuna.requestFocus();
            return;

        }
        if (this.txtCiudad.getText().trim().isEmpty()) {
            JOptionPane.showMessageDialog(null,
                    "Error debe ingresar la ciudad",
                    "Error de ingreso",
                    JOptionPane.ERROR_MESSAGE);
            this.txtCiudad.requestFocus();
            return;

        }

        if (this.txtFonos.getText().trim().isEmpty()) {
            JOptionPane.showMessageDialog(null,
                    "Error debe ingresar telefono",
                    "Error de ingreso",
                    JOptionPane.ERROR_MESSAGE);
            this.txtFonos.requestFocus();
            return;

        }

        if (this.txtMail.getText().trim().isEmpty()) {
            JOptionPane.showMessageDialog(null,
                    "Error debe ingresar el Mail",
                    "Error de ingreso",
                    JOptionPane.ERROR_MESSAGE);
            this.txtMail.requestFocus();
            return;

        }
        if (this.txtLugTrab.getText().trim().isEmpty()) {
            JOptionPane.showMessageDialog(null,
                    "Error debe ingresar el lugar de trabajo",
                    "Error de ingreso",
                    JOptionPane.ERROR_MESSAGE);
            this.txtLugTrab.requestFocus();
            return;

        }
//                if(this.txtFechaApe.getText().trim().isEmpty())
//        {
//        JOptionPane.showMessageDialog(null,
//                "Error debe ingresar el fecha de apertura",
//                "Error de ingreso",
//                JOptionPane.ERROR_MESSAGE);
//        this.txtFechaApe.requestFocus();
//        return;
//        }
        if (this.txtCupo.getText().trim().isEmpty()) {
            JOptionPane.showMessageDialog(null,
                    "Error debe ingresar el cupo",
                    "Error de ingreso",
                    JOptionPane.ERROR_MESSAGE);
            this.txtCupo.requestFocus();
            return;

        }






        // TODO add your handling code here:
        Clientes clie = new Clientes();
        validaRut vRut = new validaRut();
        negocio neg = new negocio();


        if (neg.existeRut(this.txtRut.getText()) == true) {
            // TODO agregar cliente
            // TODO se valida rut y si es verdadero ingresa rut y digito
            try {
                if (vRut.validaRut(this.txtRut.getText().trim() + "-" + this.txtDig.getText().trim()) == true) {
                    clie.setRut_cli(this.txtRut.getText().trim());
                    clie.setDigito_cli(this.txtDig.getText().trim());
                } else {
                    JOptionPane.showMessageDialog(null, "Rut no valido");
                    this.txtRut.requestFocus();
                    return;
                }
            } catch (Exception e) {
                JOptionPane.showMessageDialog(null, "Eror al escribir el rut", "Error de ingreso", JOptionPane.ERROR_MESSAGE);
                this.txtRut.requestFocus();
                return;
            }
            // fin validar rut
            // continua insertando el resto en clientes
            clie.setNombre_cli(this.txtNombre.getText().trim());
            clie.setDomicilio(this.txtDomicilio.getText().trim());
            clie.setComuna_cli(this.txtComuna.getText().trim());
            clie.setCiudad_cli(this.txtCiudad.getText().trim());
            clie.setFonos_cli(this.txtFonos.getText().trim());
            clie.setEmail_cli(this.txtMail.getText().trim());
            clie.setLugarTrabajo_cli(this.txtLugTrab.getText().trim());
            try {
                clie.setFechApe_cli(string2date(this.txtFechaApe.getText().trim()));
            } catch (ParseException ex) {
                Logger.getLogger(formCliente.class.getName()).log(Level.SEVERE, null, ex);
            }
            clie.setCupo_cli(Integer.parseInt(this.txtCupo.getText().trim()));
            clie.setSaldoDB_cli(Integer.parseInt(this.txtSaldoDB.getText().trim()));
            clie.setSaldoCR_cli(Integer.parseInt(this.txtSaldoCR.getText().trim()));
            clie.setSaldoFIN_cli(Integer.parseInt(this.txtSaldoFinal.getText().trim()));

            neg.addCliente(clie);

            JOptionPane.showMessageDialog(null, "Se ingreso corectamente\n"
                    + "Cliente: " + this.txtNombre.getText() + "\n"
                    + "Rut: " + this.txtRut.getText() + "-" + this.txtDig.getText());
            this.btnLimpiarActionPerformed(evt);
        } else {
            JOptionPane.showMessageDialog(null, "El rut ya esta ingresado");
        }
    }//GEN-LAST:event_btnAgregarClieActionPerformed

    private void btnEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarActionPerformed
        // TODO eliminar cliente
        int opcion = 0;
        opcion = JOptionPane.showConfirmDialog(this,
                "Desea eliminar registro Clientes?",
                "Eliminar Cliente", JOptionPane.YES_NO_OPTION,
                JOptionPane.QUESTION_MESSAGE);
        if (opcion == JOptionPane.YES_OPTION) {
            negocio neg = new negocio();
            JOptionPane.showMessageDialog(null, this.txtRut.getText());
            neg.eliminarRegistro(this.txtRut.getText());
            JOptionPane.showMessageDialog(null, "Se elimino corectamente\n"
                    + "Cliente: " + this.txtNombre.getText() + "\n"
                    + "Rut: " + this.txtRut.getText() + "-" + this.txtDig.getText());
            this.btnLimpiarActionPerformed(evt);

        }
    }//GEN-LAST:event_btnEliminarActionPerformed

    private void btnLimpiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLimpiarActionPerformed
        // TODO boton limpiar
        this.txtRut.setText("");
        this.txtDig.setText("");
        this.txtNombre.setText("");
        this.txtDomicilio.setText("");
        this.txtComuna.setText("");
        this.txtCiudad.setText("");
        this.txtFonos.setText("");
        this.txtLugTrab.setText("");
        this.txtFechaApe.setText("");
        this.txtCupo.setText("0");
        this.txtMail.setText("");
        this.txtSaldoCR.setText("0");
        this.txtSaldoDB.setText("0");
        this.txtSaldoFinal.setText("0");
        this.txtRenta.setText("0");

        this.deshabilitarELimYEdit();
        this.txtFechaApe.setText(date2string(Calendar.getInstance().getTime()));

    }//GEN-LAST:event_btnLimpiarActionPerformed

    private void btnEditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditarActionPerformed
        // TODO boton editar
        Clientes clie = new Clientes();
        negocio neg = new negocio();
        // Setear los datos de Acadèmico
        clie.setRut_cli(this.txtRut.getText().trim());
        clie.setNombre_cli(this.txtNombre.getText().trim());
        clie.setDomicilio(this.txtDomicilio.getText().trim());
        clie.setComuna_cli(this.txtComuna.getText().trim());
        clie.setCiudad_cli(this.txtCiudad.getText().trim());
        clie.setFonos_cli(this.txtFonos.getText().trim());
        clie.setEmail_cli(this.txtMail.getText().trim());
        clie.setLugarTrabajo_cli(this.txtLugTrab.getText().trim());
        try {
            clie.setFechApe_cli(string2date(this.txtFechaApe.getText()));
        } catch (ParseException ex) {
            Logger.getLogger(formCliente.class.getName()).log(Level.SEVERE, null, ex);
        }
        clie.setCupo_cli(Integer.parseInt(this.txtCupo.getText().trim()));
        clie.setSaldoDB_cli(Integer.parseInt(this.txtSaldoDB.getText().trim()));
        clie.setSaldoCR_cli(Integer.parseInt(this.txtSaldoCR.getText().trim()));
        clie.setSaldoFIN_cli(Integer.parseInt(this.txtSaldoFinal.getText().trim()));


        //TODO Almacenamos en base d datos
        neg.editarCliente(clie);
        JOptionPane.showMessageDialog(null, "Se edito corectamente\n"
                + "Cliente: " + this.txtNombre.getText() + "\n"
                + "Rut: " + this.txtRut.getText() + "-" + this.txtDig.getText());
        this.btnLimpiarActionPerformed(evt);
//       this.desbilitarBotones();
    }//GEN-LAST:event_btnEditarActionPerformed

    private void txtRutKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtRutKeyTyped

        if (this.txtRut.getText().trim().length() > 7) {
            evt.consume();
        }
    }//GEN-LAST:event_txtRutKeyTyped

    private void txtDigKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtDigKeyTyped
        if (this.txtDig.getText().trim().length() >= 1) {
            evt.consume();
        }
    }//GEN-LAST:event_txtDigKeyTyped

    private void txtCupoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtCupoKeyTyped
        if (evt.getKeyChar() < '0' || evt.getKeyChar() > '9') {
            evt.consume();
        }
    }//GEN-LAST:event_txtCupoKeyTyped

    private void btnBuscaNombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscaNombreActionPerformed
        // TODO buscar por nombre
        String nombre = "";
        nombre = JOptionPane.showInputDialog("Ingrese nombre a buscar");
        if (nombre != null) {
            negocio neg = new negocio();
            Clientes clie = neg.BuscarNombreCliente(nombre);

            // if ve si rut viene con datos de la forma si rut no es igual ""
            if (!clie.getRut_cli().equals("")) {
                this.txtRut.setText(clie.getRut_cli());
                this.txtDig.setText(clie.getDigito_cli());
                this.txtNombre.setText(clie.getNombre_cli());
                this.txtDomicilio.setText(clie.getDomicilio());
                this.txtComuna.setText(clie.getComuna_cli());
                this.txtCiudad.setText(clie.getCiudad_cli());
                this.txtFonos.setText(clie.getFonos_cli());
                this.txtLugTrab.setText(clie.getLugarTrabajo_cli());
                this.txtFechaApe.setText("" + date2string(clie.getFechApe_cli()));
                this.txtCupo.setText(clie.getCupo_cli() + "");
                this.txtMail.setText(clie.getEmail_cli());

                this.txtSaldoDB.setText(neg.getDebito(clie.getRut_cli()) + "");
                this.txtSaldoCR.setText(neg.getSaldoPagado(clie.getRut_cli()) + "");
                int saldoFinal = neg.getDebito(clie.getRut_cli()) - neg.getSaldoPagado(clie.getRut_cli());
                this.txtSaldoFinal.setText(saldoFinal + "");
                this.habilitarELimYEdit();

                this.habilitarELimYEdit();
            } else {
                JOptionPane.showMessageDialog(null,
                        "Error. No se encontro  cliente con esa descripción");
            }
        }


//               this.habilitarBotones();


    }//GEN-LAST:event_btnBuscaNombreActionPerformed

    private void txtNombreKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtNombreKeyTyped
        if (this.txtNombre.getText().trim().length() >= 50) {
            evt.consume();
        }
    }//GEN-LAST:event_txtNombreKeyTyped

    private void txtDomicilioKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtDomicilioKeyTyped
        if (this.txtDomicilio.getText().trim().length() >= 50) {
            evt.consume();
        }
    }//GEN-LAST:event_txtDomicilioKeyTyped

    private void txtComunaKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtComunaKeyTyped
        if (this.txtComuna.getText().trim().length() >= 30) {
            evt.consume();
        }
    }//GEN-LAST:event_txtComunaKeyTyped

    private void txtCiudadKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtCiudadKeyTyped
        if (this.txtDig.getText().trim().length() >= 30) {
            evt.consume();
        }
    }//GEN-LAST:event_txtCiudadKeyTyped

    private void txtFonosKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtFonosKeyTyped
        if (this.txtFonos.getText().trim().length() >= 30) {
            evt.consume();
        }
    }//GEN-LAST:event_txtFonosKeyTyped

    private void txtMailKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtMailKeyTyped
        if (this.txtMail.getText().trim().length() >= 30) {
            evt.consume();
        }
    }//GEN-LAST:event_txtMailKeyTyped

    private void txtLugTrabKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtLugTrabKeyTyped
        if (this.txtLugTrab.getText().trim().length() >= 50) {
            evt.consume();
        }
    }//GEN-LAST:event_txtLugTrabKeyTyped

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        this.txtFechaApe.setText(date2string(Calendar.getInstance().getTime()));

    }//GEN-LAST:event_formWindowOpened

    private void txtRentaKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtRentaKeyTyped
        if (evt.getKeyChar() < '0' || evt.getKeyChar() > '9') {
            evt.consume();
        }

        // txtCupo.setText(this.txtRenta.getText());
    }//GEN-LAST:event_txtRentaKeyTyped

    private void txtRentaKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtRentaKeyReleased
        if (!txtRenta.getText().isEmpty()) {
            txtCupo.setText(Math.round(Integer.parseInt(this.txtRenta.getText().trim()) * 0.7) + "");
        }
    }//GEN-LAST:event_txtRentaKeyReleased

    private void txtCupoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCupoActionPerformed
    }//GEN-LAST:event_txtCupoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                new formCliente().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAgregarClie;
    private javax.swing.JButton btnBuscaNombre;
    private javax.swing.JButton btnBuscaRut;
    private javax.swing.JButton btnEditar;
    private javax.swing.JButton btnEliminar;
    private javax.swing.JButton btnLimpiar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JTextField txtCiudad;
    private javax.swing.JTextField txtComuna;
    private javax.swing.JTextField txtCupo;
    private javax.swing.JTextField txtDig;
    private javax.swing.JTextField txtDomicilio;
    private javax.swing.JTextField txtFechaApe;
    private javax.swing.JTextField txtFonos;
    private javax.swing.JTextField txtLugTrab;
    private javax.swing.JTextField txtMail;
    private javax.swing.JTextField txtNombre;
    private javax.swing.JTextField txtRenta;
    private javax.swing.JTextField txtRut;
    private javax.swing.JTextField txtSaldoCR;
    private javax.swing.JTextField txtSaldoDB;
    private javax.swing.JTextField txtSaldoFinal;
    // End of variables declaration//GEN-END:variables

    public void habilitarELimYEdit() {
        this.btnEditar.setEnabled(true);
        this.btnEliminar.setEnabled(true);

        this.btnAgregarClie.setEnabled(false);

    }

    public void deshabilitarELimYEdit() {
        this.btnEditar.setEnabled(false);
        this.btnEliminar.setEnabled(false);

        this.btnAgregarClie.setEnabled(true);
    }

    private String date2string(Date fecha) {
        SimpleDateFormat df = new SimpleDateFormat("yyyy-MM-dd");
        return df.format(fecha);
    }

    private Date string2date(String dato) throws ParseException {
        SimpleDateFormat df = new SimpleDateFormat("yyyy-MM-dd");
        return df.parse(dato);
    }
}
