/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * formVentas.java
 *
 * Created on 07-may-2010, 15:16:25
 */
package capaGui;


import capaDatos.Ventas;
import capaDatos.Clientes;
import capaDatos.Vendedor;
import capaNegocio.negocio;
import java.text.DecimalFormat;
import java.text.SimpleDateFormat;
import java.util.Calendar;
import java.util.Date;
import java.util.Iterator;

import javax.swing.JOptionPane;

/**
 *
 * @author BORO
 */
public class formVentas extends javax.swing.JFrame {

    /** Creates new form formVentas */
    public formVentas() {
        initComponents();
        this.setLocationRelativeTo(null);
        this.btnEditar.setEnabled(false);
        this.btnEliminar.setEnabled(false);
        this.llenaCombo();
        
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jEditorPane1 = new javax.swing.JEditorPane();
        jPanel1 = new javax.swing.JPanel();
        txtInteres = new javax.swing.JTextField();
        txtNumDoc = new javax.swing.JTextField();
        txtValor = new javax.swing.JTextField();
        txtFechMov = new javax.swing.JTextField();
        txtMonto = new javax.swing.JTextField();
        txtDescrip = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        txtTipMov = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        txtMontoFinal = new javax.swing.JTextField();
        txtSucursal = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        txtDigito = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        txtNombre = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        cbxCuotas = new javax.swing.JComboBox();
        txtRut = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        cbxTipoDoc = new javax.swing.JComboBox();
        ckbContado = new javax.swing.JCheckBox();
        cbxRutVendedor = new javax.swing.JComboBox();
        btnAgregarVta = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        btnEditar = new javax.swing.JButton();
        btnEliminar = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        btnBuscaRut = new javax.swing.JButton();
        btnLimpiar = new javax.swing.JButton();

        jScrollPane1.setViewportView(jEditorPane1);

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Formulario de ventas");
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Venta"));

        txtInteres.setEditable(false);
        txtInteres.setText("0");
        txtInteres.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtInteresKeyTyped(evt);
            }
        });

        txtNumDoc.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtNumDocKeyTyped(evt);
            }
        });

        txtValor.setEditable(false);
        txtValor.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtValorKeyTyped(evt);
            }
        });

        txtFechMov.setEditable(false);

        txtMonto.setText("0");
        txtMonto.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtMontoFocusLost(evt);
            }
        });
        txtMonto.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtMontoKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtMontoKeyTyped(evt);
            }
        });

        txtDescrip.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtDescripKeyTyped(evt);
            }
        });

        jLabel3.setText("Tipo de movimiento :");

        jLabel4.setText("Fecha de venta :");

        jLabel1.setText("Rut cliente :");

        txtTipMov.setEditable(false);
        txtTipMov.setText("1");
        txtTipMov.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtTipMovActionPerformed(evt);
            }
        });
        txtTipMov.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtTipMovKeyTyped(evt);
            }
        });

        jLabel13.setText("Sucursal :");

        jLabel12.setText("Vendedor :");

        txtMontoFinal.setEditable(false);

        txtSucursal.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtSucursalKeyTyped(evt);
            }
        });

        jLabel11.setText("Descripción :");

        txtDigito.setEditable(false);

        jLabel10.setText("Tipo de documento :");

        jLabel9.setText("Nº Documento :");

        jLabel8.setText("Interes :");

        jLabel7.setText("Valor de la cuota :");

        jLabel5.setText("Monto :");

        jLabel6.setText("Nº cuotas:");

        jLabel2.setText("Nombre del cliente :");

        jButton1.setText("Buscar Cliente");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        txtNombre.setEditable(false);

        jLabel14.setText("Monto final :");

        cbxCuotas.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Selec...", "1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12", "0" }));
        cbxCuotas.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cbxCuotasItemStateChanged(evt);
            }
        });

        txtRut.setEditable(false);

        jLabel15.setText("%");

        cbxTipoDoc.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Selec...", "Boleta", "Factura" }));

        ckbContado.setText("Pago en efectivo");
        ckbContado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ckbContadoActionPerformed(evt);
            }
        });

        cbxRutVendedor.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Seleccione un Rut vendedor..." }));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(43, 43, 43)
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtRut, javax.swing.GroupLayout.DEFAULT_SIZE, 103, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtDigito, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(7, 7, 7)
                        .addComponent(jButton1))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtNombre, javax.swing.GroupLayout.DEFAULT_SIZE, 237, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel10)
                            .addComponent(jLabel13)
                            .addComponent(jLabel12)
                            .addComponent(jLabel11)
                            .addComponent(jLabel9)
                            .addComponent(jLabel8)
                            .addComponent(jLabel7)
                            .addComponent(jLabel6)
                            .addComponent(jLabel5)
                            .addComponent(jLabel4)
                            .addComponent(jLabel3))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtNumDoc, javax.swing.GroupLayout.DEFAULT_SIZE, 239, Short.MAX_VALUE)
                            .addComponent(txtDescrip, javax.swing.GroupLayout.DEFAULT_SIZE, 239, Short.MAX_VALUE)
                            .addComponent(txtFechMov, javax.swing.GroupLayout.DEFAULT_SIZE, 239, Short.MAX_VALUE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(cbxCuotas, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(ckbContado))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(txtInteres, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel15))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(txtValor, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 146, Short.MAX_VALUE)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(txtMonto, javax.swing.GroupLayout.DEFAULT_SIZE, 82, Short.MAX_VALUE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jLabel14)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtMontoFinal, javax.swing.GroupLayout.DEFAULT_SIZE, 87, Short.MAX_VALUE))
                            .addComponent(txtSucursal, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cbxTipoDoc, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtTipMov, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cbxRutVendedor, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtDigito, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton1)
                    .addComponent(txtRut, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 25, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txtTipMov, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(txtFechMov, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(txtMonto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel14)
                    .addComponent(txtMontoFinal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(cbxCuotas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ckbContado))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(txtValor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(txtInteres, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel15))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(txtNumDoc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(cbxTipoDoc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(txtDescrip, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel12)
                    .addComponent(cbxRutVendedor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel13)
                    .addComponent(txtSucursal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(25, 25, 25))
        );

        btnAgregarVta.setFont(new java.awt.Font("Tahoma", 1, 14));
        btnAgregarVta.setIcon(new javax.swing.ImageIcon(getClass().getResource("/capaImagenes/agregar.png"))); // NOI18N
        btnAgregarVta.setText("Ingresar Venta");
        btnAgregarVta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAgregarVtaActionPerformed(evt);
            }
        });

        jPanel4.setBorder(javax.swing.BorderFactory.createTitledBorder(""));

        btnEditar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/capaImagenes/editar.png"))); // NOI18N
        btnEditar.setText("Editar");
        btnEditar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditarActionPerformed(evt);
            }
        });

        btnEliminar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/capaImagenes/eliminarpng.png"))); // NOI18N
        btnEliminar.setText("Eliminar");
        btnEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnEliminar, javax.swing.GroupLayout.DEFAULT_SIZE, 177, Short.MAX_VALUE)
                    .addComponent(btnEditar, javax.swing.GroupLayout.DEFAULT_SIZE, 177, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addComponent(btnEditar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnEliminar))
        );

        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder("Buscar Venta"));

        btnBuscaRut.setIcon(new javax.swing.ImageIcon(getClass().getResource("/capaImagenes/buscar.png"))); // NOI18N
        btnBuscaRut.setText("Buscar por Rut");
        btnBuscaRut.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscaRutActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnBuscaRut, javax.swing.GroupLayout.DEFAULT_SIZE, 177, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addComponent(btnBuscaRut)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        btnLimpiar.setText("Limpiar texto");
        btnLimpiar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLimpiarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(btnAgregarVta, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 217, Short.MAX_VALUE)
                    .addComponent(btnLimpiar, javax.swing.GroupLayout.DEFAULT_SIZE, 217, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnAgregarVta, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 47, Short.MAX_VALUE)
                        .addComponent(btnLimpiar)))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnBuscaRutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscaRutActionPerformed
        String rut = "";
        rut = JOptionPane.showInputDialog("Ingrese rut a buscar sin digito verificador");
        if (rut != null) {
            negocio neg = new negocio();
            Ventas vta = neg.getBuscarVentas(rut);
            Clientes clie = neg.getBuscarClientes(rut);

            if (!vta.getRut_vta().equals("")) {
                this.txtRut.setText(clie.getRut_cli());
                this.txtDigito.setText(clie.getDigito_cli());
                this.txtNombre.setText(clie.getNombre_cli());
                this.txtTipMov.setText("" + vta.getTipoMov_vta());
                this.txtFechMov.setText(date2string(vta.getFecha_vta()));
                this.txtMonto.setText("" + vta.getMonto_vta());
                if(vta.getNumCuota_vta()!=13){
                    this.cbxCuotas.setSelectedIndex(vta.getNumCuota_vta());
                    }else{this.ckbContado.setSelected(true);}
                this.txtValor.setText("" + vta.getValorCuota_vta());
                this.txtInteres.setText("" + vta.getInteresCuota_vta());
                this.txtNumDoc.setText("" + vta.getDocu_vta());
                this.cbxTipoDoc.setSelectedItem(vta.getTipoDoc_vta());
                this.txtDescrip.setText(vta.getDescrip_vta());
                this.cbxRutVendedor.setSelectedItem(vta.getVendedor_vta());
                this.txtSucursal.setText(vta.getSucursal_vta());

                this.habilitarELimYEdit();
            } else {
                JOptionPane.showMessageDialog(null, "Error. Venta no existe");
            }

        }

}//GEN-LAST:event_btnBuscaRutActionPerformed

    private void btnAgregarVtaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgregarVtaActionPerformed

        //TODO errores de campo vacio
        if (this.txtRut.getText().trim().isEmpty()) {
            JOptionPane.showMessageDialog(null,
                    "Error debe ingresar el rut",
                    "Error de ingreso",
                    JOptionPane.ERROR_MESSAGE);
            this.txtRut.requestFocus();
            return;

        }
        if (this.txtTipMov.getText().trim().isEmpty()) {
            JOptionPane.showMessageDialog(null,
                    "Error debe ingresar el tipo de movimiento",
                    "Error de ingreso",
                    JOptionPane.ERROR_MESSAGE);
            this.txtTipMov.requestFocus();
            return;

        }

        if (this.txtMonto.getText().trim().isEmpty() || this.txtMonto.getText().trim().equalsIgnoreCase("0")) {
            JOptionPane.showMessageDialog(null,
                    "Error debe ingresar el monto",
                    "Error de ingreso",
                    JOptionPane.ERROR_MESSAGE);
            this.txtMonto.requestFocus();
            return;

        }
        if (this.cbxCuotas.getSelectedIndex() == 0) {
            JOptionPane.showMessageDialog(null,
                    "Error debe seleccionar numero de cuotas",
                    "Error de ingreso",
                    JOptionPane.ERROR_MESSAGE);
            this.cbxCuotas.requestFocus();
            return;

        }
        if (this.txtNumDoc.getText().trim().isEmpty()) {
            JOptionPane.showMessageDialog(null,
                    "Error debe ingresar el Nº de documento",
                    "Error de ingreso",
                    JOptionPane.ERROR_MESSAGE);
            this.txtNumDoc.requestFocus();
            return;

        }
        if (this.cbxTipoDoc.getSelectedIndex() == 0) {
            JOptionPane.showMessageDialog(null,
                    "Error debe seleccionar tipo de documento",
                    "Error de ingreso",
                    JOptionPane.ERROR_MESSAGE);
            this.cbxTipoDoc.requestFocus();
            return;

        }
        if (this.txtDescrip.getText().trim().isEmpty()) {
            JOptionPane.showMessageDialog(null,
                    "Error debe ingresar una descripción",
                    "Error de ingreso",
                    JOptionPane.ERROR_MESSAGE);
            this.txtDescrip.requestFocus();
            return;

        }
        if (this.cbxRutVendedor.getSelectedIndex()==0) {
            JOptionPane.showMessageDialog(null,
                    "Error debe ingresar un vendedor",
                    "Error de ingreso",
                    JOptionPane.ERROR_MESSAGE);
            this.cbxRutVendedor.requestFocus();
            return;

        }
        if (this.txtSucursal.getText().trim().isEmpty()) {
            JOptionPane.showMessageDialog(null,
                    "Error debe ingresar una sucursal",
                    "Error de ingreso",
                    JOptionPane.ERROR_MESSAGE);
            this.txtSucursal.requestFocus();
            return;
        }

//        if(this.esDeudor()){
//            return;
//        }
        negocio neg = new negocio();
        // Consulto cupo
        double cupoCliente = neg.getCupo(this.txtRut.getText());
        double pendiente = neg.getDebito(this.txtRut.getText()); //***********
        double verificaCupo = cupoCliente -(pendiente + Integer.parseInt(this.txtMonto.getText()));
        if(this.ckbContado.isSelected()==true){verificaCupo=1;}

        if(verificaCupo>=0){
        Ventas vta = new Ventas();
        
        if(neg.existeDocumento(Integer.parseInt(this.txtNumDoc.getText()))==true){

        vta.setRut_vta(this.txtRut.getText().trim());
        vta.setDigito_vta(this.txtDigito.getText().trim());
        vta.setTipoMov_vta(Integer.parseInt(this.txtTipMov.getText().trim()));
        vta.setFecha_vta(Calendar.getInstance().getTime());
        vta.setMonto_vta(Integer.parseInt(this.txtMontoFinal.getText().trim()));
        vta.setNumCuota_vta(this.cbxCuotas.getSelectedIndex());
        vta.setValorCuota_vta(Integer.parseInt(this.txtValor.getText().trim()));
        vta.setInteresCuota_vta(Double.parseDouble(this.txtInteres.getText().trim()));
        vta.setDocu_vta(Integer.parseInt(this.txtNumDoc.getText().trim()));
        vta.setTipoDoc_vta((String) this.cbxTipoDoc.getSelectedItem());
        vta.setDescrip_vta(this.txtDescrip.getText().trim());
        vta.setVendedor_vta((String)this.cbxRutVendedor.getSelectedItem());
        vta.setSucursal_vta(this.txtSucursal.getText().trim());
        if(this.ckbContado.isSelected()==false){}
        String nombre = this.txtNombre.getText();
        neg.addVentas(vta,this.cbxCuotas.getSelectedIndex(),nombre);
        System.out.println(vta);
        String rutVendedor=(String)this.cbxRutVendedor.getSelectedItem();
        JOptionPane.showMessageDialog(null, "Se ingreso correctamente la venta\n" +
        "Vendedor: "+neg.getNomVendedor(rutVendedor));
        double ventasVend = neg.getVentasVendedor(rutVendedor);
        double nuevoTotalVentas = ventasVend + Integer.parseInt(this.txtMontoFinal.getText().trim());
        neg.editVentasVend(rutVendedor,nuevoTotalVentas);

        this.btnLimpiarActionPerformed(evt);
        }else{JOptionPane.showMessageDialog(null, "Numero Documento ya  ingresado");}
        }else{JOptionPane.showMessageDialog(null, "La venta supera el cupo del cliente");}
    }//GEN-LAST:event_btnAgregarVtaActionPerformed

    private void btnEditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditarActionPerformed
        Ventas vta = new Ventas();
        negocio neg = new negocio();

        vta.setRut_vta(this.txtRut.getText().trim());
        vta.setDigito_vta(this.txtDigito.getText().trim());
        vta.setTipoMov_vta(Integer.parseInt(this.txtTipMov.getText().trim()));
        vta.setFecha_vta(Calendar.getInstance().getTime());
        vta.setMonto_vta(Integer.parseInt(this.txtMontoFinal.getText().trim()));
        vta.setNumCuota_vta(this.cbxCuotas.getSelectedIndex());
        vta.setValorCuota_vta(Integer.parseInt(this.txtValor.getText().trim()));
        vta.setInteresCuota_vta(Double.parseDouble(this.txtInteres.getText().trim()));
        vta.setDocu_vta(Integer.parseInt(this.txtNumDoc.getText().trim()));
        vta.setTipoDoc_vta((String) this.cbxTipoDoc.getSelectedItem());
        vta.setDescrip_vta(this.txtDescrip.getText().trim());
        vta.setVendedor_vta((String) this.cbxTipoDoc.getSelectedItem());
        vta.setSucursal_vta(this.txtSucursal.getText().trim());
        this.deshabilitarBotones();

        neg.editarVenta(vta);
        System.out.println(vta);
        JOptionPane.showMessageDialog(null, "Se edito correctamente la venta");
        this.btnLimpiarActionPerformed(evt);

    }//GEN-LAST:event_btnEditarActionPerformed

    private void btnEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarActionPerformed
        int opcion = 0;
        opcion = JOptionPane.showConfirmDialog(this,
                "Desea eliminar registro Clientes?",
                "Eliminar Cliente", JOptionPane.YES_NO_OPTION,
                JOptionPane.QUESTION_MESSAGE);
        if (opcion == JOptionPane.YES_OPTION) {
            negocio neg = new negocio();
            neg.deleteVentas(this.txtRut.getText().trim());
//            this.limpiar();
            JOptionPane.showMessageDialog(null, "Se elimino correctamente la venta");
            this.btnLimpiarActionPerformed(evt);
            this.deshabilitarBotones();
            this.btnLimpiarActionPerformed(evt);
        }


    }//GEN-LAST:event_btnEliminarActionPerformed

    private void txtTipMovActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTipMovActionPerformed
    }//GEN-LAST:event_txtTipMovActionPerformed

    private void txtTipMovKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtTipMovKeyTyped
        if (evt.getKeyChar() < '0' || evt.getKeyChar() > '9') {
            evt.consume();
        } else {
            if (this.txtTipMov.getText().trim().length() > 0) {
                evt.consume();
            }
        }


    }//GEN-LAST:event_txtTipMovKeyTyped

    private void txtMontoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtMontoKeyTyped
        if (evt.getKeyChar() < '0' || evt.getKeyChar() > '9') {
            evt.consume();
        }
        if (this.txtMonto.getText().isEmpty()) {
            this.txtMonto.setText("" + 0);
        }
    }//GEN-LAST:event_txtMontoKeyTyped

    private void txtValorKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtValorKeyTyped
        if (evt.getKeyChar() < '0' || evt.getKeyChar() > '9') {
            evt.consume();
        }
    }//GEN-LAST:event_txtValorKeyTyped

    private void txtInteresKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtInteresKeyTyped
        if (evt.getKeyChar() < '0' || evt.getKeyChar() > '9') {
            evt.consume();
        }
    }//GEN-LAST:event_txtInteresKeyTyped

    private void txtNumDocKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtNumDocKeyTyped
        if (evt.getKeyChar() < '0' || evt.getKeyChar() > '9') {
            evt.consume();
        }
    }//GEN-LAST:event_txtNumDocKeyTyped

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        String rut = "";
        rut = JOptionPane.showInputDialog("Ingrese rut a buscar sin digito verificador");
        if (rut != null) {
            negocio neg = new negocio();
            Ventas vta = neg.getBuscarVentas(rut);
            Clientes clie = neg.getBuscarClientes(rut);

            if (!clie.getRut_cli().equals("")) {
                this.txtRut.setText(clie.getRut_cli());
                this.txtDigito.setText(clie.getDigito_cli());
                this.txtNombre.setText(clie.getNombre_cli());
            } else {
                JOptionPane.showMessageDialog(null, "Error. Rut no existe");
            }

        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void cbxCuotasItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cbxCuotasItemStateChanged
        // TODO add your handling code here:
        this.txtInteres.setText("0");
        double montoFinal;
        int mf;
        this.txtMontoFinal.setText(this.txtMonto.getText());
        if (this.cbxCuotas.getSelectedIndex() == 4
                || this.cbxCuotas.getSelectedIndex() == 5
                || this.cbxCuotas.getSelectedIndex() == 6) {
            montoFinal = Integer.parseInt(this.txtMonto.getText())
                    + (Integer.parseInt(this.txtMonto.getText()) * 0.2);
            mf = (int) montoFinal;
            this.txtMontoFinal.setText(mf + "");
            this.txtInteres.setText("2");
        } else {
            if (this.cbxCuotas.getSelectedIndex() == 7
                    || this.cbxCuotas.getSelectedIndex() == 8
                    || this.cbxCuotas.getSelectedIndex() == 9
                    || this.cbxCuotas.getSelectedIndex() == 10
                    || this.cbxCuotas.getSelectedIndex() == 11
                    || this.cbxCuotas.getSelectedIndex() == 12) {
                montoFinal = Integer.parseInt(this.txtMonto.getText())
                        + (Integer.parseInt(this.txtMonto.getText()) * 0.35);
                mf = (int) montoFinal;
                this.txtMontoFinal.setText(mf + "");
                this.txtInteres.setText("0.35");

            }

        }
        if (this.cbxCuotas.getSelectedIndex() != 0) {
            double valorCuota = Double.parseDouble(this.txtMontoFinal.getText())
                    / this.cbxCuotas.getSelectedIndex();
            int vc = (int) valorCuota;
            this.txtValor.setText(vc + "");
        }






    }//GEN-LAST:event_cbxCuotasItemStateChanged

    private void txtMontoFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtMontoFocusLost
        // TODO add your handling code here:
    }//GEN-LAST:event_txtMontoFocusLost

    private void txtMontoKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtMontoKeyReleased
        // TODO add your handling code here:
        int cuota = this.cbxCuotas.getSelectedIndex();
        this.cbxCuotasItemStateChanged(null);

    }//GEN-LAST:event_txtMontoKeyReleased

    private void btnLimpiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLimpiarActionPerformed

        this.txtRut.setText("");
        this.txtDigito.setText("");
        this.txtNombre.setText("");
//        this.txtTipMov.setText("");
//        this.txtFechMov.setText("");
        this.txtFechMov.setText(date2string(Calendar.getInstance().getTime()));
        this.txtMonto.setText("0");
        this.txtMontoFinal.setText("");
        this.cbxCuotas.setSelectedIndex(0);
        this.txtValor.setText("");
        this.txtInteres.setText("");
        this.txtNumDoc.setText("");
        this.cbxTipoDoc.setSelectedIndex(0);
        this.txtDescrip.setText("");
        this.cbxRutVendedor.setSelectedIndex(0);
        this.txtSucursal.setText("");
        this.ckbContado.setSelected(false);



        this.deshabilitarELimYEdit();
    }//GEN-LAST:event_btnLimpiarActionPerformed

    private void txtDescripKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtDescripKeyTyped
        if (this.txtDescrip.getText().trim().length() >= 30) {
            evt.consume();
        }
    }//GEN-LAST:event_txtDescripKeyTyped

    private void txtSucursalKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtSucursalKeyTyped
        if (this.txtSucursal.getText().trim().length() >= 30) {
            evt.consume();
        }
    }//GEN-LAST:event_txtSucursalKeyTyped

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        this.txtFechMov.setText(date2string(Calendar.getInstance().getTime()));

    }//GEN-LAST:event_formWindowOpened

    private void ckbContadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ckbContadoActionPerformed
        // TODO add your handling code here:
        if(this.ckbContado.isSelected()==true){
        this.cbxCuotas.setSelectedIndex(13);
        this.cbxCuotas.setEnabled(false);
        this.txtValor.setText("0");
        }else{this.cbxCuotas.setEnabled(true);
              this.cbxCuotas.setSelectedIndex(0);
              
        }
    }//GEN-LAST:event_ckbContadoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                new formVentas().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAgregarVta;
    private javax.swing.JButton btnBuscaRut;
    private javax.swing.JButton btnEditar;
    private javax.swing.JButton btnEliminar;
    private javax.swing.JButton btnLimpiar;
    private javax.swing.JComboBox cbxCuotas;
    private javax.swing.JComboBox cbxRutVendedor;
    private javax.swing.JComboBox cbxTipoDoc;
    private javax.swing.JCheckBox ckbContado;
    private javax.swing.JButton jButton1;
    private javax.swing.JEditorPane jEditorPane1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField txtDescrip;
    private javax.swing.JTextField txtDigito;
    private javax.swing.JTextField txtFechMov;
    private javax.swing.JTextField txtInteres;
    private javax.swing.JTextField txtMonto;
    private javax.swing.JTextField txtMontoFinal;
    private javax.swing.JTextField txtNombre;
    private javax.swing.JTextField txtNumDoc;
    private javax.swing.JTextField txtRut;
    private javax.swing.JTextField txtSucursal;
    private javax.swing.JTextField txtTipMov;
    private javax.swing.JTextField txtValor;
    // End of variables declaration//GEN-END:variables

    public void habilitarBotones() {
        this.btnEditar.setEnabled(true);
        this.btnEliminar.setEnabled(true);

        this.btnBuscaRut.setEnabled(false);
    }

    public void deshabilitarBotones() {
        this.btnEditar.setEnabled(false);
        this.btnEliminar.setEnabled(false);

        this.btnBuscaRut.setEnabled(true);
    }
    private DecimalFormat df = new DecimalFormat("#,###");

    public void habilitarELimYEdit() {
        this.btnEditar.setEnabled(true);
        this.btnEliminar.setEnabled(true);

        this.btnAgregarVta.setEnabled(false);

    }

    public void deshabilitarELimYEdit() {
        this.btnEditar.setEnabled(false);
        this.btnEliminar.setEnabled(false);

        this.btnAgregarVta.setEnabled(true);

    }

    private String date2string(Date fecha) {
        SimpleDateFormat df = new SimpleDateFormat("dd/MM/yyyy");
        return df.format(fecha);
    }

    private void llenaCombo(){
        negocio neg=new negocio();
        Iterator it=neg.rutVendedores().iterator();
        while(it.hasNext()){
            Vendedor vend= (Vendedor) it.next();
            this.cbxRutVendedor.addItem(vend.getRutVendedor());
            
        }


    }

//    public boolean esDeudor() {
//        Date hoy = Calendar.getInstance().getTime();
//        negocio neg = new negocio();
//        Iterator it = neg.getDocuPendientes().iterator();
//
//        while (it.hasNext()) {
//            DocuPendientes docu = (DocuPendientes) it.next();
//            if (docu.getFechUltimo_docu().before(hoy)) {
//                if(docu.getRut_docu().equals(this.txtRut.getText().trim())){
//                 JOptionPane.showMessageDialog(null,
//                    "Usted es un deudor, No puede comprar, Además está en DICOM",
//                    "Error de venta",
//                    JOptionPane.ERROR_MESSAGE);
//                this.txtNumDoc.requestFocus();
//                return true;
//                }
//            }
//        }
//        return false;
//    }
}
