/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * formDocPendientes.java
 *
 * Created on 07-may-2010, 17:25:32
 */
package capaGui;

import capaDatos.DocuPendientes;
import capaDatos.Clientes;
import capaNegocio.negocio;
import java.text.SimpleDateFormat;
import java.util.Calendar;
import java.util.Date;
import javax.swing.JOptionPane;

/**
 *
 * @author BORO
 */
public class formDocPendientes extends javax.swing.JFrame {

    /** Creates new form formDocPendientes */
    public formDocPendientes() {
        initComponents();
        this.setLocationRelativeTo(null);
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        txtAbonos = new javax.swing.JTextField();
        txtMonto = new javax.swing.JTextField();
        txtTipDoc = new javax.swing.JTextField();
        txtFechUltimo = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        txtNombre = new javax.swing.JTextField();
        txtRut = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        txtDigito = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        txtNumDoc = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        btnBuscaRut = new javax.swing.JButton();
        btnBuscaNombre = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        btnEditar = new javax.swing.JButton();
        btnEliminar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Formulario documentos pendientes");

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Buscar documento pendiente"));

        txtAbonos.setEnabled(false);

        txtMonto.setEnabled(false);

        txtTipDoc.setEnabled(false);

        txtFechUltimo.setEnabled(false);

        jLabel3.setText("Nombre cliente :");

        jLabel1.setText("Rut cliente :");

        txtNombre.setEnabled(false);

        txtRut.setEnabled(false);

        jLabel11.setText("Fecha ultimo pago :");

        txtDigito.setEnabled(false);

        jLabel10.setText("Tipo de documento :");

        jLabel5.setText("Monto :");

        txtNumDoc.setEnabled(false);

        jLabel6.setText("Abonos :");

        jLabel14.setText("Nº documento :");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel10)
                    .addComponent(jLabel14))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(txtTipDoc, javax.swing.GroupLayout.DEFAULT_SIZE, 118, Short.MAX_VALUE)
                    .addComponent(txtNumDoc, javax.swing.GroupLayout.DEFAULT_SIZE, 118, Short.MAX_VALUE))
                .addGap(37, 37, 37))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel6)
                    .addComponent(jLabel3)
                    .addComponent(jLabel1)
                    .addComponent(jLabel11)
                    .addComponent(jLabel5))
                .addGap(4, 4, 4)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(txtMonto, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 120, Short.MAX_VALUE)
                    .addComponent(txtFechUltimo, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 120, Short.MAX_VALUE)
                    .addComponent(txtAbonos, javax.swing.GroupLayout.DEFAULT_SIZE, 120, Short.MAX_VALUE)
                    .addComponent(txtNombre, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 120, Short.MAX_VALUE)
                    .addComponent(txtRut, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 120, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtDigito, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtRut, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1)
                    .addComponent(txtDigito, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txtNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtTipDoc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel10))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtNumDoc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel14))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtMonto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtAbonos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtFechUltimo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel11)))
        );

        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder("Buscar cliente"));

        btnBuscaRut.setIcon(new javax.swing.ImageIcon(getClass().getResource("/capaImagenes/buscar.png"))); // NOI18N
        btnBuscaRut.setText("Buscar por Rut");
        btnBuscaRut.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscaRutActionPerformed(evt);
            }
        });

        btnBuscaNombre.setIcon(new javax.swing.ImageIcon(getClass().getResource("/capaImagenes/buscar.png"))); // NOI18N
        btnBuscaNombre.setText("Buscar por nombre");
        btnBuscaNombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscaNombreActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btnBuscaRut, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 179, Short.MAX_VALUE)
                    .addComponent(btnBuscaNombre, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addComponent(btnBuscaRut)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnBuscaNombre)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(""));

        btnEditar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/capaImagenes/editar.png"))); // NOI18N
        btnEditar.setText("Editar");
        btnEditar.setEnabled(false);
        btnEditar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditarActionPerformed(evt);
            }
        });

        btnEliminar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/capaImagenes/eliminarpng.png"))); // NOI18N
        btnEliminar.setText("Eliminar");
        btnEliminar.setEnabled(false);
        btnEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(105, 105, 105)
                .addComponent(btnEditar, javax.swing.GroupLayout.DEFAULT_SIZE, 143, Short.MAX_VALUE)
                .addGap(73, 73, 73)
                .addComponent(btnEliminar, javax.swing.GroupLayout.DEFAULT_SIZE, 143, Short.MAX_VALUE)
                .addGap(34, 34, 34))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnEditar)
                    .addComponent(btnEliminar))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jPanel2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnBuscaRutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscaRutActionPerformed
        String rut = "";
        rut = JOptionPane.showInputDialog("Ingrese rut a buscar sin digito verificador");
        if (rut != null) {
            negocio neg = new negocio();
            DocuPendientes docu = neg.getBuscarDocuPendientes(rut);
            Clientes clie = neg.getBuscarClientes(rut);
            if (!clie.getRut_cli().equals("")) {
                this.txtRut.setText(clie.getRut_cli());
                this.txtDigito.setText(clie.getDigito_cli());
                this.txtNombre.setText(docu.getNomCli_docu());
                this.txtTipDoc.setText(docu.getTipoDoc_docu());
                this.txtNumDoc.setText("" + docu.getNumDoc_docu());
                this.txtMonto.setText("" + docu.getMontoPen_docu());
                this.txtAbonos.setText("" + docu.getAbonos_docu());
                this.txtFechUltimo.setText(date2string(docu.getFechUltimo_docu()));
                this.habilitar();

            } else {
                JOptionPane.showMessageDialog(null, "Error. Rut no existe");
            }

        }
}//GEN-LAST:event_btnBuscaRutActionPerformed

    private void btnBuscaNombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscaNombreActionPerformed
        String nombre = "";
        String rut = "";
        nombre = JOptionPane.showInputDialog("Ingrese nombre a buscar");
if (nombre != null) {
        negocio neg = new negocio();
        Clientes clie = neg.BuscarNombreCliente(nombre);
        rut = clie.getRut_cli();
        DocuPendientes docu = neg.getBuscarDocuPendientes(rut);


        // if ve si rut viene con datos de la forma si rut no es igual ""
        if (!clie.getRut_cli().equals("")) {
            this.txtRut.setText(docu.getRut_docu());
            this.txtDigito.setText(docu.getDigito_docu());
            this.txtNombre.setText(docu.getNomCli_docu());
            this.txtTipDoc.setText(docu.getTipoDoc_docu());
            this.txtNumDoc.setText("" + docu.getNumDoc_docu());
            this.txtMonto.setText("" + docu.getMontoPen_docu());
            this.txtAbonos.setText("" + docu.getAbonos_docu());
            this.txtFechUltimo.setText(date2string(docu.getFechUltimo_docu()));
            this.habilitar();


        } else {
            JOptionPane.showMessageDialog(null,
                    "Error. No se encontro Documento con esa descripción");
        }
}
    }//GEN-LAST:event_btnBuscaNombreActionPerformed

    private void btnEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarActionPerformed
        int opcion = 0;
        opcion = JOptionPane.showConfirmDialog(this,
                "Desea eliminar registro de Documento Pendiente?",
                "Eliminar Documento Pendiente", JOptionPane.YES_NO_OPTION,
                JOptionPane.QUESTION_MESSAGE);
        if (opcion == JOptionPane.YES_OPTION) {
            negocio neg = new negocio();
            neg.eliminarDocuPendiente(this.txtRut.getText().trim());
            this.limpiar();
            this.deshabilitar();
        }
    }//GEN-LAST:event_btnEliminarActionPerformed

    private void btnEditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditarActionPerformed
        DocuPendientes docu = new DocuPendientes();
        negocio neg = new negocio();

        docu.setRut_docu(this.txtRut.getText().trim());
        docu.setDigito_docu(this.txtDigito.getText().trim());
        docu.setNomCli_docu(this.txtNombre.getText().trim());
        docu.setTipoDoc_docu(this.txtTipDoc.getText().trim());
        docu.setNumDoc_docu(Integer.parseInt(this.txtNumDoc.getText().trim()));
        docu.setMontoPen_docu(Integer.parseInt(this.txtMonto.getText().trim()));
        docu.setAbonos_docu(Integer.parseInt(this.txtAbonos.getText().trim()));
        docu.setFechUltimo_docu(Calendar.getInstance().getTime());
        this.deshabilitar();
        neg.editarDocuPendientes(docu);
        System.out.println(docu);
    }//GEN-LAST:event_btnEditarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                new formDocPendientes().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBuscaNombre;
    private javax.swing.JButton btnBuscaRut;
    private javax.swing.JButton btnEditar;
    private javax.swing.JButton btnEliminar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JTextField txtAbonos;
    private javax.swing.JTextField txtDigito;
    private javax.swing.JTextField txtFechUltimo;
    private javax.swing.JTextField txtMonto;
    private javax.swing.JTextField txtNombre;
    private javax.swing.JTextField txtNumDoc;
    private javax.swing.JTextField txtRut;
    private javax.swing.JTextField txtTipDoc;
    // End of variables declaration//GEN-END:variables

    private void habilitar() {
        this.txtRut.setEnabled(true);
        this.txtDigito.setEnabled(true);
        this.txtNombre.setEnabled(true);
        this.txtTipDoc.setEnabled(true);
        this.txtNumDoc.setEnabled(true);
        this.txtMonto.setEnabled(true);
        this.txtAbonos.setEnabled(true);
        this.txtFechUltimo.setEnabled(true);

        this.btnEditar.setEnabled(true);
        this.btnEliminar.setEnabled(true);
        this.btnBuscaNombre.setEnabled(false);
        this.btnBuscaRut.setEnabled(false);
    }

    private void deshabilitar() {
        this.txtRut.setEditable(false);
        this.txtDigito.setEditable(false);
        this.txtNombre.setEditable(false);
        this.txtTipDoc.setEditable(false);
        this.txtNumDoc.setEditable(false);
        this.txtMonto.setEditable(false);
        this.txtAbonos.setEditable(false);
        this.txtFechUltimo.setEditable(false);

        this.btnEditar.setEnabled(false);
        this.btnEliminar.setEnabled(false);
        this.btnBuscaNombre.setEnabled(true);
        this.btnBuscaRut.setEnabled(true);
    }

    private void limpiar() {
        this.txtRut.setText("");
        this.txtDigito.setText("");
        this.txtNombre.setText("");
        this.txtTipDoc.setText("");
        this.txtNumDoc.setText("");
        this.txtMonto.setText("");
        this.txtAbonos.setText("");
        this.txtFechUltimo.setText("");
    }
    private String date2string(Date fecha)
    {
        SimpleDateFormat df = new SimpleDateFormat("yyyy-MM-dd");
        return df.format(fecha);
    }
}
