/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * formPagos.java
 *
 * Created on 07-may-2010, 16:56:21
 */
package capaGui;

import capaDatos.DocuPendientes;
import capaDatos.Pagos;
import capaDatos.Ventas;
import capaDatos.Clientes;
import capaDatos.DocuCancelados;
import capaDatos.Documento;
import capaNegocio.negocio;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.Calendar;
import java.util.Date;
import java.util.GregorianCalendar;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author BORO
 */
public class formPagos extends javax.swing.JFrame {

    /** Creates new form formPagos */
    public formPagos() {
        initComponents();
        this.setLocationRelativeTo(null);

    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        txtDocPaga = new javax.swing.JTextField();
        txtFechPago = new javax.swing.JTextField();
        txtMonto = new javax.swing.JTextField();
        txtDescrip = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        txtTipMov = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        lblcaja = new javax.swing.JLabel();
        txtRut = new javax.swing.JTextField();
        txtSucursal = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        txtDigito = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        txtCaja = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        txtNumDoc = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        cmbTipoDoc = new javax.swing.JComboBox();
        btnBuscarDocu = new javax.swing.JButton();
        txtCuotaPaga = new javax.swing.JTextField();
        txtCuota = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        txtMontoCuota = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        btnBuscaDocu = new javax.swing.JButton();
        btnAgregar = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Formulario de pagos");

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Pagos", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION));

        txtDocPaga.setEditable(false);
        txtDocPaga.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtDocPagaKeyTyped(evt);
            }
        });

        txtFechPago.setEditable(false);

        txtMonto.setEditable(false);
        txtMonto.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtMontoKeyTyped(evt);
            }
        });

        jLabel3.setText("Tipo de movimiento :");

        jLabel4.setText("Fecha de pago :");

        jLabel1.setText("Rut cliente :");

        txtTipMov.setEditable(false);
        txtTipMov.setText("2");
        txtTipMov.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtTipMovKeyTyped(evt);
            }
        });

        jLabel13.setText("Sucursal :");

        lblcaja.setText("Caja :");

        txtRut.setEditable(false);

        jLabel11.setText("Descripción :");

        txtDigito.setEditable(false);

        jLabel10.setText("Tipo de documento :");

        txtCaja.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtCajaKeyTyped(evt);
            }
        });

        jLabel5.setText("Monto adeudado:");

        jLabel9.setText("Documento que paga :");

        txtNumDoc.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtNumDocKeyTyped(evt);
            }
        });

        jLabel14.setText("Nº documento :");

        cmbTipoDoc.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Seleccione...", "Cheque", "Tarjeta de Crédito", "Tarjeta de Débito", "Efectivo" }));

        btnBuscarDocu.setText("...");
        btnBuscarDocu.setEnabled(false);
        btnBuscarDocu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarDocuActionPerformed(evt);
            }
        });

        txtCuotaPaga.setEditable(false);

        txtCuota.setEditable(false);

        jLabel2.setText("Cuota que paga :");

        jLabel6.setText("de");

        txtMontoCuota.setEditable(false);

        jLabel7.setText("Monto de cuota :");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel9)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtDocPaga, javax.swing.GroupLayout.DEFAULT_SIZE, 106, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnBuscarDocu, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel14)
                                    .addComponent(jLabel10))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED))
                            .addComponent(jLabel11)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(lblcaja)
                                    .addComponent(jLabel13))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(cmbTipoDoc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(txtDescrip, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 106, Short.MAX_VALUE)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(txtCaja, javax.swing.GroupLayout.DEFAULT_SIZE, 106, Short.MAX_VALUE))
                                    .addComponent(txtSucursal, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 106, Short.MAX_VALUE)
                                    .addComponent(txtNumDoc, javax.swing.GroupLayout.DEFAULT_SIZE, 106, Short.MAX_VALUE))
                                .addGap(8, 8, 8)))
                        .addGap(30, 30, 30)))
                .addGap(14, 14, 14))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtCuotaPaga, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(6, 6, 6)
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtCuota, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(77, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel5)
                    .addComponent(jLabel4)
                    .addComponent(jLabel3)
                    .addComponent(jLabel1)
                    .addComponent(jLabel7))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(txtMontoCuota, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 106, Short.MAX_VALUE)
                    .addComponent(txtMonto, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 106, Short.MAX_VALUE)
                    .addComponent(txtRut, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 106, Short.MAX_VALUE)
                    .addComponent(txtFechPago, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 106, Short.MAX_VALUE)
                    .addComponent(txtTipMov, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtDigito, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(25, 25, 25))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtRut, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1)
                    .addComponent(txtDigito, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txtTipMov, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(txtFechPago, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(txtMonto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtMontoCuota, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtCuotaPaga, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtCuota, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2)
                    .addComponent(jLabel6))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtDocPaga, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9)
                    .addComponent(btnBuscarDocu))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(cmbTipoDoc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(3, 3, 3)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtNumDoc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel14))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtDescrip, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel11))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtCaja, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblcaja))
                .addGap(9, 9, 9)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtSucursal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel13)))
        );

        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder("Buscar boleta o factura a pagar"));

        btnBuscaDocu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/capaImagenes/buscar.png"))); // NOI18N
        btnBuscaDocu.setText("Buscar Factura / Boleta");
        btnBuscaDocu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscaDocuActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnBuscaDocu, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(btnBuscaDocu, javax.swing.GroupLayout.DEFAULT_SIZE, 143, Short.MAX_VALUE)
        );

        btnAgregar.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnAgregar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/capaImagenes/agregar.png"))); // NOI18N
        btnAgregar.setText("Ingresar pago");
        btnAgregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAgregarActionPerformed(evt);
            }
        });

        jButton1.setText("Limpiar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(btnAgregar, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(31, 31, 31)
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 181, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton1))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnAgregar, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnBuscaDocuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscaDocuActionPerformed
        String docu = "";
        docu = JOptionPane.showInputDialog("Ingrese el numero de documento que va a cancelar");
        if (docu != null) {
            negocio neg = new negocio();
            Documento doc = neg.getBuscarDocumento(docu);

            if (!doc.getRut_docu().equals("")) {

                this.txtRut.setText(doc.getRut_docu());
                this.txtDigito.setText(doc.getDigito_docu());
                this.txtFechPago.setText(doc.getFechUltimo_docu()+"");
                if(doc.getCuotaActual_docu()==0){
                    int cuota = doc.getCuotaActual_docu()+1;
                    this.txtCuotaPaga.setText(cuota+"");
                    }else{
                    this.txtCuotaPaga.setText(doc.getCuotaActual_docu()+"");
                    }
                this.txtCuota.setText(doc.getCuota_docu()+"");
                this.txtDocPaga.setText(doc.getNumDoc_docu()+"");
                this.txtMonto.setText(doc.getMontoPen_docu()+"");

                int cuota = neg.getDocuVentas(Integer.parseInt(docu));
                this.txtMontoCuota.setText(cuota+"");
//                this.txtTipMov.setText("" + pago.getTipoMov_pago());
//                //this.txtFechPago.setText(pago.getFech_pago());
//                this.txtMonto.setText("" + pago.getMonto_pago());
//                this.txtDocPaga.setText("" + pago.getDocu_pago());
//                this.cmbTipoDoc.setSelectedItem(pago.getTipoDoc_pago());
//                this.txtNumDoc.setText("" + pago.getNumDoc_pago());
//                this.txtDescrip.setText(pago.getDescrip_pago());
//                this.txtCaja.setText("" + pago.getCaja_pago());
//                this.txtSucursal.setText(pago.getSucursal_pago());
//                this.habilitarBotones();
            } else {
                JOptionPane.showMessageDialog(null, "Error. Boleta/Factura no existe");
            }

        }
}//GEN-LAST:event_btnBuscaDocuActionPerformed
    private void btnAgregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgregarActionPerformed
        if (this.txtRut.getText().trim().isEmpty()) {
            JOptionPane.showMessageDialog(null,
                    "Error debe ingresar el rut",
                    "Error de ingreso",
                    JOptionPane.ERROR_MESSAGE);
            this.txtRut.requestFocus();
            return;
        }
        if (this.txtDigito.getText().trim().isEmpty()) {
            JOptionPane.showMessageDialog(null,
                    "Error debe ingresar el digito",
                    "Error de ingreso",
                    JOptionPane.ERROR_MESSAGE);
            this.txtDigito.requestFocus();
            return;
        }
        if (this.txtTipMov.getText().trim().isEmpty()) {
            JOptionPane.showMessageDialog(null,
                    "Error debe ingresar el tipo de movimiento",
                    "Error de ingreso",
                    JOptionPane.ERROR_MESSAGE);
            this.txtTipMov.requestFocus();
            return;
        }

        if (this.txtMonto.getText().trim().isEmpty()) {
            JOptionPane.showMessageDialog(null,
                "Error debe ingresar el monto",
                "Error de ingreso",
                JOptionPane.ERROR_MESSAGE);
        this.txtMonto.requestFocus();
        return;
        }
        if(this.txtDocPaga.getText().trim().isEmpty()){
            JOptionPane.showMessageDialog(null,
                "Error debe ingresar el documento a pagar",
                "Error de ingreso",
                JOptionPane.ERROR_MESSAGE);
        this.txtDocPaga.requestFocus();
        return;
        }
        if(this.cmbTipoDoc.getSelectedIndex()==0){
            JOptionPane.showMessageDialog(null,
                "Error debe ingresar el tipo de documento",
                "Error de ingreso",
                JOptionPane.ERROR_MESSAGE);
        this.cmbTipoDoc.requestFocus();
        return;
        }
        if(this.txtNumDoc.getText().trim().isEmpty()){
            JOptionPane.showMessageDialog(null,
                "Error debe ingresar el numero del documento",
                "Error de ingreso",
                JOptionPane.ERROR_MESSAGE);
        this.txtNumDoc.requestFocus();
        return;
        }
        if(this.txtDescrip.getText().trim().isEmpty()){
            JOptionPane.showMessageDialog(null,
                "Error debe ingresar una descripcion",
                "Error de ingreso",
                JOptionPane.ERROR_MESSAGE);
        this.txtDescrip.requestFocus();
        return;
        }
        if(this.txtCaja.getText().trim().isEmpty()){
            JOptionPane.showMessageDialog(null,
                "Error debe ingresar la caja",
                "Error de ingreso",
                JOptionPane.ERROR_MESSAGE);
        this.txtCaja.requestFocus();
        return;
        }
        if(this.txtSucursal.getText().trim().isEmpty()){
            JOptionPane.showMessageDialog(null,
                "Error debe ingresar la sucursal",
                "Error de ingreso",
                JOptionPane.ERROR_MESSAGE);
        this.txtSucursal.requestFocus();
        return;
        }

                // -----------  modificando docu pendiente ---------
// Sumo uno a la cuota actual antes de guardar
        int cuota = Integer.parseInt(this.txtCuotaPaga.getText()) + 1;
        // resto el monto de la cuota al monto total adeudado
        int montoNuevo = Integer.parseInt(this.txtMonto.getText()) - Integer.parseInt(this.txtMontoCuota.getText());

        int bono=0;

        int documento = Integer.parseInt(this.txtDocPaga.getText());
        System.out.println(cuota + " " + montoNuevo + " " + documento);
        negocio neg = new negocio();
        bono= neg.getAbono(documento)+Integer.parseInt(this.txtMontoCuota.getText());

        String rutcito = this.txtRut.getText().trim();

        if (montoNuevo != 0) {
            try {
                Date dato = string2date(this.txtFechPago.getText());
                Calendar cal = new GregorianCalendar();
                cal.setTime(dato);
                cal.add(Calendar.MONTH, 1);
                String fecha = date2string(cal.getTime());
                // metodo update para docu-pendiente numDOc, cuota, fecha ssiguiente y monto de como quedo
                neg.editarPendiente(documento, cuota, fecha, montoNuevo,bono);
                Pagos pago = new Pagos();

                pago.setRut_pago(this.txtRut.getText().trim());
                pago.setDigito_pago(this.txtDigito.getText().trim());
                pago.setTipoMov_pago(Integer.parseInt(this.txtTipMov.getText().trim()));
                pago.setFech_pago(Calendar.getInstance().getTime());
                pago.setMonto_pago(Integer.parseInt(this.txtMontoCuota.getText().trim()));
                pago.setDocu_pago(Integer.parseInt(this.txtDocPaga.getText().trim()));
                pago.setTipoDoc_pago((String) this.cmbTipoDoc.getSelectedItem());
                pago.setNumDoc_pago(Integer.parseInt(this.txtNumDoc.getText().trim()));
                pago.setDescrip_pago(this.txtDescrip.getText().trim());
                pago.setCaja_pago(Integer.parseInt(this.txtCaja.getText().trim()));
                pago.setSucursal_pago(this.txtSucursal.getText().trim());
                neg.addPagos(pago);

                this.limpiar();
                JOptionPane.showMessageDialog(this, "Pago efecuado correctamente",
                                         "Pago", JOptionPane.INFORMATION_MESSAGE);


            } catch (ParseException ex) {
                Logger.getLogger(formPagos.class.getName()).log(Level.SEVERE, null, ex);
            }
            } else {
            Pagos pago = new Pagos();
            pago.setRut_pago(this.txtRut.getText().trim());
            pago.setDigito_pago(this.txtDigito.getText().trim());
            pago.setTipoMov_pago(Integer.parseInt(this.txtTipMov.getText().trim()));
            pago.setFech_pago(Calendar.getInstance().getTime());
            pago.setMonto_pago(Integer.parseInt(this.txtMontoCuota.getText().trim()));
            pago.setDocu_pago(Integer.parseInt(this.txtDocPaga.getText().trim()));
            pago.setTipoDoc_pago((String) this.cmbTipoDoc.getSelectedItem());
            pago.setNumDoc_pago(Integer.parseInt(this.txtNumDoc.getText().trim()));
            pago.setDescrip_pago(this.txtDescrip.getText().trim());
            pago.setCaja_pago(Integer.parseInt(this.txtCaja.getText().trim()));
            pago.setSucursal_pago(this.txtSucursal.getText().trim());
            neg.addPagos(pago);

            
            DocuCancelados cans = new DocuCancelados();
            cans.setRut_cancel(pago.getRut_pago());
            cans.setDigito_cancel(pago.getDigito_pago());
            cans.setNomCli_cancel(rutcito);
            cans.setTipoDoc_cancel(pago.getTipoDoc_pago());
            cans.setNumDoc_cancel(pago.getNumDoc_pago());
            cans.setMontoTotal_cancel(pago.getMonto_pago());
            cans.setFechUltimoPago_docu(pago.getFech_pago());
            neg.addDocuCancelado(cans);
            neg.borrarDocuPendiente(documento);
            this.limpiar();

            JOptionPane.showMessageDialog(this, "Ha terminado de pagar todas sus" +
                            " deudas", "Pago", JOptionPane.INFORMATION_MESSAGE);
        }
    }//GEN-LAST:event_btnAgregarActionPerformed

    private void txtTipMovKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtTipMovKeyTyped
        if (evt.getKeyChar() < '0' || evt.getKeyChar() > '9') {
            evt.consume();
        } else {
            if (this.txtTipMov.getText().trim().length() > 1) {
                evt.consume();
            }
        }
    }//GEN-LAST:event_txtTipMovKeyTyped

    private void txtMontoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtMontoKeyTyped
        if (evt.getKeyChar() < '0' || evt.getKeyChar() > '9') {
            evt.consume();
        }
    }//GEN-LAST:event_txtMontoKeyTyped

    private void txtDocPagaKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtDocPagaKeyTyped
        if (evt.getKeyChar() < '0' || evt.getKeyChar() > '9') {
            evt.consume();
        }
    }//GEN-LAST:event_txtDocPagaKeyTyped

    private void txtNumDocKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtNumDocKeyTyped
        if (evt.getKeyChar() < '0' || evt.getKeyChar() > '9') {
            evt.consume();
        }

    }//GEN-LAST:event_txtNumDocKeyTyped

    private void txtCajaKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtCajaKeyTyped
        if (evt.getKeyChar() < '0' || evt.getKeyChar() > '9') {
            evt.consume();
        }
    }//GEN-LAST:event_txtCajaKeyTyped

    private void btnBuscarDocuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarDocuActionPerformed
        negocio neg=new negocio();
        DocuPendientes docu = neg.getBuscarDocuPendientes(Integer.parseInt(this.txtDocPaga.getText().trim()));
        this.txtMonto.setText(""+docu.getMontoPen_docu());
        this.txtFechPago.setText(date2string(docu.getFechUltimo_docu()));
        this.txtNumDoc.setText(""+docu.getDocu_docu());
        
    }//GEN-LAST:event_btnBuscarDocuActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        this.limpiar();
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                new formPagos().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAgregar;
    private javax.swing.JButton btnBuscaDocu;
    private javax.swing.JButton btnBuscarDocu;
    private javax.swing.JComboBox cmbTipoDoc;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JLabel lblcaja;
    private javax.swing.JTextField txtCaja;
    private javax.swing.JTextField txtCuota;
    private javax.swing.JTextField txtCuotaPaga;
    private javax.swing.JTextField txtDescrip;
    private javax.swing.JTextField txtDigito;
    private javax.swing.JTextField txtDocPaga;
    private javax.swing.JTextField txtFechPago;
    private javax.swing.JTextField txtMonto;
    private javax.swing.JTextField txtMontoCuota;
    private javax.swing.JTextField txtNumDoc;
    private javax.swing.JTextField txtRut;
    private javax.swing.JTextField txtSucursal;
    private javax.swing.JTextField txtTipMov;
    // End of variables declaration//GEN-END:variables

    private void habilitarBotones() {


        this.btnBuscaDocu.setEnabled(false);

    }

    private void deshabilitarBotones() {


        this.btnBuscaDocu.setEnabled(true);

    }

    private void limpiar() {
        this.txtRut.setText("");
        this.txtDigito.setText("");
        this.txtFechPago.setText("");
        this.txtMonto.setText("");
        this.txtDocPaga.setText("");
        this.cmbTipoDoc.setSelectedIndex(0);
        this.txtNumDoc.setText("");
        this.txtDescrip.setText("");
        this.txtCaja.setText("");
        this.txtSucursal.setText("");
        this.txtTipMov.requestFocus();
        this.txtMontoCuota.setText("");
        this.txtCuotaPaga.setText("");
        this.txtCuota.setText("");
    }
    private String date2string(Date fecha)
    {
        SimpleDateFormat df = new SimpleDateFormat("yyyy-MM-dd");
        return df.format(fecha);
    }
    private Date string2date(String dato) throws ParseException {
        SimpleDateFormat df = new SimpleDateFormat("yyyy-MM-dd");
        return df.parse(dato);
    }
}
